### ISSUE TITLE
Don't lose form data on reload

### ISSUE THREAD

**Issue by suluke** [nickcmaynard/jsonschemalint#6]
I suppose this would be easy to implement using webstorage. I found [this stackoverflow](https://stackoverflow.com/questions/17591447/how-to-reload-current-page-without-losing-any-form-data) while researching how this could be solved easily. Thanks for considering this

**Comment by nickcmaynard** [comment]
What use case would this solve?  Are users habitually reloading the page?

**Comment by suluke** [comment]
At least I did when I used your service :D Since this was some time ago, I am not quite sure why I was repeatedly closing the site. I think I (ab)used it as some sort of web-IDE for my rather complex schema

**Comment by nickcmaynard** [comment]
That's OK - that's what I use it for as well.  I just don't reload very often :).  Let's leave this around - others can chime in and we'll see what happens in a few months.

Out of interest - is there an alternative?  If it's better, I'll just trash this and redirect people.

**Comment by suluke** [comment]
A quick google search gave me this: http://www.jsonschemavalidator.net/
I have no experience with it. I found your site (was it on the official json schema website?) and liked it because it's open source. I don't have a use case any more, so I won't be much help when it comes to answering your question whether to maintain this or not.

**Comment by HotelDon** [comment]
I wouldn't mind taking a crack at implementing webstorage, accidentally reloading can be a pain in the ass for me sometimes. As for JSON Schema Validator, I can already tell you it's worse than JSON Schema Lint because it doesn't support YAML, and it also doesn't support v5.

YAML support is great because the native "YAML schemas" either lack complex features to maintain compatibility with different languages, or are so poorly documented that using them is impossible. And not only am I too lazy to add draft5 support to JSV, it appears to be closed source, so I couldn't even if I wanted to. Which, of course, automatically makes JSL the better choice.

**Comment by nickcmaynard** [comment]
@HotelDon would be great to see that, thank you.

**Comment by nickcmaynard** [comment]
Closed by #12.
